# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  #主题作者: http://xiguabaobao.com
  #热前端: http://reqianduan.com
  Yunyao Zhang: http://aidaiz.com/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: yunhuanran

# Baidu share
baidushare: true

# Baidu tongji
baidu_tongji: true